export enum LanguageTags {
    "en" = "en",
    "es" = "es",
    "fr" = "fr",
    "de" = "de",
    "zh" = "zh",
    "ja" = "ja",
    "pt" = "pt",
    "ru" = "ru",
    "it" = "it",
    'da' = 'da',
    'ko' = 'ko',
    'nl' = 'nl',
    'no' = 'no',
    'sv' = 'sv',
}
